name: Sync Image to Docker hub or Aliyun  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PW }}
        logout: false

    - name: Login to Aliyun Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.DOCKER_ALIYUN_USER }}
        password: ${{ secrets.DOCKER_ALIYUN_PW }}
        logout: false

    # - name: Login to HW Hub
    #   uses: docker/login-action@v2.2.0
    #   with:
    #     registry: swr.cn-north-4.myhuaweicloud.com
    #     username: ${{ secrets.DOCKER_HW_USER }}
    #     password: ${{ secrets.DOCKER_HW_PW }}
    #     logout: false
        
    - name: Login to YOZO Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: hub.yozosoft.com:4431
        username: ${{ secrets.DOCKER_YOZO_USER }}
        password: ${{ secrets.DOCKER_YOZO_PW }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        skopeo -v
        sh ./script/sysnc-images.sh
